build-package:
  tags:
    - bigbuilds
    - strit
  script:
    - if [ -f /opt/dependencies/qt5-es2-declarative-* ]; then sudo pacman -U /opt/dependencies/qt5-es2-declarative-* --noconfirm; fi;
    - sudo pacman -Syy && makepkg -scr --noconfirm
    - cp ./*.pkg.tar.* /opt/dependencies/
  artifacts:
    paths:
    - ./*.pkg.tar.*
    expire_in: 1 week
